server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: product-server
  datasource:
    type:
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop
    username: root
    password: 03102896528
  rabbitmq:
    host: localhost
    port: 15672
    username: rabbitadmin
    password: 123456